apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: gitops/apps
    repoURL: <REPO_URL>
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
